// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzjrriowohvgqseuvdvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56anJyaW93b2h2Z3FzZXV2ZHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTAyNTUsImV4cCI6MjA2NjU2NjI1NX0.980SYATZap8_4XmtWSCDFzM_2qRDhre8opHbZHom2WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});